apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jenkins.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jenkins.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.name }}
        - name: {{ .Values.volume.dockerVolumeName }}
          hostPath:
            path: {{ .Values.volume.dockerVolumePath }}
      securityContext:
        fsGroup: 1000 
        runAsUser: 0
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containePort }}
              protocol: TCP
          livenessProbe:
            tcpSocket: 
              port: {{ .Values.containePort }}
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: {{ .Values.containePort }}
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountPath }}
            - name: {{ .Values.volume.dockerVolumeName }}
              mountPath: {{ .Values.volume.dockerVolumePath }}
        
